spring:
  application:
    name: bank-star
  datasource:
    url: jdbc:h2:/Users/mariamorozova/Downloads/transaction.mv.db
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public

server:
  port: 8080

logging:
  level:
    com.project.Bank_star: DEBUG
    ProjectAndRules: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE