spring.application.name=Bank-star
server.port=8080

spring.datasource.url=jdbc:h2:/Users/mariamorozova/Downloads/transaction.mv.db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.liquibase.enabled=false

spring.cache.cache-names=userCache,ruleCache,transactionCache
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=600s

logging.level.com.project.Bank_star=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.cache=TRACE
# Telegram Bot Configuration
telegram.bot.token=8231305315:AAEAeHNa-IY4e-3N3g2vDFp7mEcrppFdw2Y
telegram.bot.name=BankStarBankBot
