spring.application.name=Bank-star
server.port=8081

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=bank-star.app:user
spring.datasource.password=money

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.liquibase.enabled=false

logging.level.com.project.Bank_star=DEBUG
logging.level.org.hibernate.SQL=DEBUG